"""empty message

Revision ID: 06468ed31b11
Revises: ef83c51ca456
Create Date: 2023-02-25 21:08:49.065068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06468ed31b11'
down_revision = 'ef83c51ca456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['user_id'], ['id'])
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
